### ISSUE TITLE
SimHash based RDSE, Scalar, Document encoders? Compared to existing RDSE

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#527]
From @brev in https://github.com/htm-community/nupic.cpp/pull/278#issuecomment-503890320 

Hi @ctrl-z-9000-times, 
Thanks for all the code. I'm curious about your new hash-based RDSE approach.  My C++ skills aren't up-to-speed enough to read the code very well yet, if you wouldn't mind a question?

I'm wondering about this property of SDRs:

> Similar inputs should have high overlap.  
> Overlap decreases smoothly as inputs become less similar.

I know the original random RDSE provided this by making sure neighbor bucket SDRs only differed by 2 bits (starting with the random seed). An SDR that was 2 buckets away would differ by 4 bits, 3 buckets away would differ by 6, etc.

I can't quite tell how you're accomplishing this here. I'm guessing I don't understand C++ well enough, if you wouldn't mind explaining? Or, maybe MurmurHash3 has some [Locality Sensitive Hashing](https://en.wikipedia.org/wiki/Locality-sensitive_hashing) properties?

I recently explored hash-based encoding with my [SimHash](https://en.wikipedia.org/wiki/SimHash) [Scalar](https://discourse.numenta.org/t/new-simhash-distributed-scalar-encoder-shadse/5860) and [Document](https://discourse.numenta.org/t/also-simhash-document-encoder/5893) encoders (which use locality-sensitive hashing).  I'm planning on making C++ versions of those, but perhaps you've already found a better way here, and/or I can learn a few things before starting.

Also, I understand that MurmurHash3 can output only 32-bit and 128-bit digests. How do you go about making a variable-length SDR output from that?

Thanks much!   (and, thanks @breznak for leading me here).

**Comment by ctrl-z-9000-times** [comment]
Hi @brev,

This RDSE is described in section 3.2 of the paper "Encoding Data for HTM Systems" https://arxiv.org/pdf/1602.05925.pdf

I found this paper very informative, and recommend reading it.

**Comment by brev** [comment]
@ctrl-z-9000-times thanks, but unfortunately that doesn't help me understand your specific implementation. :)

I'm wondering:

1) How are you ensuring that nearby buckets have more similar representations than far away buckets?

2) How are you taking  a 32- or 128-bit hash digest, and spreading that out to be the desired output bit length of the SDR?  (i.e. n=400 bits)

thanks much.

**Comment by ctrl-z-9000-times** [comment]
Hi Brev,

> 1) How are you ensuring that nearby buckets have more similar representations than far away buckets?

Section 3.1 of the document describes how the normal scalar encoder works.  The scalar encoder has the semantic similarity property that you're looking for.

Section 3.2 describes the RDSE which is an extension of the scalar encoder which allows it to encode an arbitrary range of values.  The RDSE keeps the semantic similarity property from the scalar encoder.

> 2) How are you taking a 32- or 128-bit hash digest, and spreading that out to be the desired output bit length of the SDR? (i.e. n=400 bits)

It doesn't work like that.  The RDSE essentially contains a scalar encoder, and the index of each active bit in the scalar encoding is mapped (using the hash) to an output bit in the RDSE.  This allows the scalar encoder to have an infinite range of output which is mapped to the RDSE's finite number of bits.

HTH

**Comment by ctrl-z-9000-times** [comment]
I wrote a short script to demonstrate the semantic similarity properties of the RDSE (currently only works on branch "update-readme").
```python
python3
import numpy as np
from htm import *
from htm.encoders.rdse import *

enc = RDSE_Parameters()
enc.size = 1000
enc.sparsity = .1
enc.radius = 1
enc = RDSE( enc )

A = enc.encode( 0 )
B = []
X = np.linspace( -2, 2, num = 400 )
for i in X:
    B.append( enc.encode( i ).getOverlap( A ) )

import matplotlib.pyplot as plt
plt.plot( X, B )
plt.title("RDSE Semantic Similarity Properties")
plt.xlabel("Input Value")
plt.ylabel("Overlap With Input = 0")
plt.text(-2, 75, "RDSE Parameters\n  size = 1,000\n  activeBits = 100\n  radius = 1")
plt.show()
```

![Figure_1](https://user-images.githubusercontent.com/19578795/59966365-e3b39a00-94e9-11e9-8ca3-8c66c6ab1e2c.png)

**Comment by brev** [comment]
Thanks @ctrl-z-9000-times, let me study that, and get back to you.  I appreciate the time!

**Comment by brev** [comment]
OK @ctrl-z-9000-times, I am fully on board with you now! (finally).

I misread Section 3.2 of "Encoding Data for HTM Systems". I had content hashing on my brain at the time, and missed that it was talking about index hashing, thus missing the whole point.

What a beautiful, simple, and clever solution.  I'm glad you were paying attention.

Thanks again for your help and patience. :)

This makes my "SimHash **Scalar** Encoder" overkill, as your current `htm.core` scalar encoder beats it on every point.  Mine essentially does the same through content hashing instead of index hashing, badly abusing a document similarity scheme.  I'll make a note on Discourse that it is deprecated, and to use the one in already in `htm.core`.

I still plan on coding up my SimHash **Document** Encoder still in the near future, as it still shows usefulness.

A few follow-on thoughts (cc @breznak):

1. Perhaps we should call this the "Hashing Scalar Encoder", as "Scalar" and "RDSE" encoders are already standardized terms in Old NuPIC?

2. I'd like to see an option to output the SDR pre-hashing, if you want an original-style encoding (which may also solve Issue #470).

Also, FYI, I just noticed _another_ encoding method I missed before, the "Sampling Linear" Scalar Encoder. If I understand correctly, this is an ideal solution for a Min/Max Scalar Encoder, in the same way that the current `htm.core` Scalar Encoder is ideal for an unbounded Scalar range.  Link:
http://mrcslws.com/gorilla/?path=hotgym.clj#a_third_way
   
thanks!

**Comment by brev** [comment]
@breznak  I believe this can be closed.
