### ISSUE TITLE
Implement Serializable interface

### ISSUE THREAD

**Issue by breznak** [htm-community/htm.core#59]
for proper, clean serialization

API: 
 - void save()
 - static T load()
 - struct params {} 
   - here are all constructor parameters that need to be serialized (will also be used for Comparable) 

TODO: 
discuss details of the API
Part of #58

**Comment by dkeeney** [comment]
struct params is good...I have added that in a few places so that binary
serialization can just write the structure but remember it cannot be used
that way if it contains any pointers (std::string for example).
Serialization needs to save state...not just the parameters so not
everything is a parameter. I have use struct loc_ in places but anything
would work.

I disagree on load()...only because we already have it as void load().

**Comment by dkeeney** [comment]
Like I said...void load() has always been there...on all of the objects. I
would rather not be re-designing things we don't need to until we get this
all put together.  I love to change things just because I think it would
look nicer or be more useful but I have to restrain myself (most of the
time). :)

**Comment by breznak** [comment]
Fixed in #62 , hurayy! :100:

**Comment by breznak** [comment]
The <<, and >> operators for serialization remained commented out, what do you think of enabling them?

**Comment by breznak** [comment]
> Some objects use << and >> for a human readable serialization and therefore would have both << && >> as well as save() and load(). 

I see. Would method signitures differentiate between stringstream << (print), and outputstream << (serialize) ? 

> In that last push I removed the comments but I guess that did not make it into the code merged. 

So should we uncomment?

**Comment by breznak** [comment]
@dkeeney I've now noticed eg `Random` contains `operator<<` used as a serialization method, as well as tests for it. 
Have we fully switched to Cereal and its `save/load , *_ar` "API", and the `<<` can be removed? 

I'm trying to simplify the codebase as I'm debugging the random seed in SP.

**Comment by dkeeney** [comment]
Sure, you can remove << from Random.

**Comment by breznak** [comment]
All classes now should use only `Serializable` API for serialization
