### ISSUE TITLE
Python setup.py Help

### ISSUE THREAD

**Issue by be4pro** [htm-community/htm.core#716]
Hi,
I followed Simple Python build in Readme with `python setup.py install` and met the following error
>...
...
running build_ext
building 'htm.dummy' extension
error: Unable to find a compatible Visual Studio installation.

I assume there are setting issues on my computer but I don't know what they are. I've installed VS 2019, got `C:\Program Files (x86)\Microsoft Visual Studio\Installer` in PATH, and I can run `c++ --help` in command prompt. What else should I do?

.........................................

While deleting build folder created fromthe above and following Simple Build On Windows (MS Visual Studio 2017 or 2019), the last step `python setup.py install --prefix=` outputs ValueError
>E:\Python37\Lib\site-packages\setuptools\dist.py:474: UserWarning: Normalizing 'v2.0.22' to '2.0.22'
  normalized_version,
running install
Traceback (most recent call last):
  File "setup.py", line 441, in <module>
    "htm-bindings-check = htm.bindings.check:checkMain",
  File "E:\Python37\Lib\site-packages\setuptools\__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "E:\Python37\lib\distutils\core.py", line 148, in setup
    dist.run_commands()
  File "E:\Python37\lib\distutils\dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "E:\Python37\lib\distutils\dist.py", line 984, in run_command
    cmd_obj.ensure_finalized()
  File "E:\Python37\lib\distutils\cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "E:\Python37\Lib\site-packages\setuptools\command\install.py", line 38, in finalize_options
    orig.install.finalize_options(self)
  File "E:\Python37\lib\distutils\command\install.py", line 346, in finalize_options
    'userbase', 'usersite')
  File "E:\Python37\lib\distutils\command\install.py", line 487, in convert_paths
    setattr(self, attr, convert_path(getattr(self, attr)))
  File "E:\Python37\lib\distutils\util.py", line 110, in convert_path
    raise ValueError("path '%s' cannot be absolute" % pathname)
ValueError: path '/Lib/site-packages' cannot be absolute

Getting so close!!

..............................................

The unit test showed 1 FAILED though. Other 338 tests PASSED.
>[ RUN      ] DirectoryTest.Iterator
ERR:  CHECK FAILED: "!ec" removeTree: directory is not empty。 [D:\Project J.A.R.V.I.S\HTM\htm.core-master\htm.core\src\htm\os\Directory.cpp line 90]
unknown file: error: C++ exception with description "CHECK FAILED: "!ec" removeTree: directory is not empty。" thrown in the test body.
[  FAILED  ] DirectoryTest.Iterator (7 ms)

**Comment by dkeeney** [comment]
Hmmm, this should have worked.
I am using the command:  `python3 setup.py install --user --force`
You can use just `python` in that command if `python --version` gives you version 3.6 or better.  
Anacondra python is not officially supported for htm.core but may work.  I think it is the one installed by MSVC.  Try the latest python from python.org.

The error in the DirectoryTest is one that I have not seen before.  It should remove everything in a directory before deleting the directory.  I will have to check that out.

**Comment by be4pro** [comment]
`python --version` is 3.7.4
I try your suggestion `python setup.py install --user --force`, the error goes
>...
building 'htm.dummy' extension
error: Unable to find a compatible Visual Studio installation.

I'm still looking for the reasons that got me these errors.

**Comment by dkeeney** [comment]
As far as I can tell, the error is coming from the setup() function in setup.py when it tries to compile dummy.c which is part of the .egg package.  But I cannot determine why it cannot find the MSVC compiler.

Something to try:
Use `pip list` to see if you already have htm.core installed from some other installation.  If you do, try removing it by running a command prompt as 'admin' and then give the command `pip uninstall htm.core`.  There may be more than one so you might have to do this more than once.  Then use the command `python setup.py install --user --force`

If that does not help.  We can make sure the library can be built with MSVC 2019.  
- delete the `build/` folder.
- double click on `startupMSVC.bat`

This should find MSVC and configure it.  When the .bat script completes, press any key to startup Visual Studio.  If this does not start up maybe there is some indication as to why.  This can be used to do a full build if you are working with C++ but does not build the python interface.  So after you finish playing with that, delete the `build/` directory again and then try `python setup.py install --user --force`.  My thinking is that maybe Visual Studio needs to be ran once to initialize things before it can be used by the python build....just a guess.

Let me know how it goes.  We really need to know how to fix this problem because others might have this problem as well.

Thanks

**Comment by dkeeney** [comment]
I don't know if this applies to your situation or not but thought I would mention it anyway...
I have both MSVC 2017 and MSVC 2019 installed.  If I run the command `python setup.py install --user --force` in a command prompt for MSVC 2017 it will fail with strange error messages that say something about incompatibility of tool set because it is trying to use MSVC 2019.  

If I really want to use MSVC 2017 in this case I have to do the following:
```
set NC_CMAKE_GENERATOR="Visual Studio 15 2017 Win64"
python setup.py install --user --force
```

What I found was that it is better to use a plain ordinary Command Prompt window instead to avoid the conflict.  It will just use the newest MSVC.

**Comment by be4pro** [comment]
Following your suggestions.
1. `pip uninstall htm.core`, then `python setup.py install --user --force`. Same error
>...
...
running build_py
running build_ext
building 'htm.dummy' extension
error: Unable to find a compatible Visual Studio installation.

2. Delete `build/` folder, click `startupMSVC.bat`, press any key to start MSVC, follow the Readme instructions to build everything under `release`, `x64` config. The last output goes
> ===== 8 succeed, 0 failed, 0 updated, 5 skipped =====

Then delete `build/` and run `python setup.py install --user --force`, same error
>...
...
copying src\htm\bindings\sdr.cp37-win_amd64.pyd -> build\lib.win-amd64-3.7\htm\bindings
copying src\htm\examples\gymdata.csv -> build\lib.win-amd64-3.7\htm\examples
running build_ext
building 'htm.dummy' extension
error: Unable to find a compatible Visual Studio installation.

I have VS2019 and VS Code, so I try `set NC_CMAKE_GENERATOR="Visual Studio 16 2019 Win64"`
and run `python setup.py install --user --force` in plain cmd prompt, in VS code and VS2019. They all got me the same error.

I had CMake 3.15.4 installed. Do I need to set something in CMake after the installment?
or are there specific env variables I need to set in the path?

**Comment by dkeeney** [comment]
Wow, you tried everything.

The only variable that seems different from my own installation is that you have VS Code.  I cannot see how that would affect it.

There are no env variables that need to be set or anything to install other than to make sure you have python3, CMake, and Visual Studio installed.   The installation CMake script downloads and installs all of the other dependencies.

I just am out of ideas as to why it will not build for you.

You could try skipping the build all together and do a pip install.  We are still working on this so it might not work for you.  It does not work for me... This will download and install a pre-built wheel from the public PYPI test server.
```
python -m pip install --upgrade pip setuptools wheel
pip install --user --force --index-url https://test.pypi.org/simple   htm.core
```

You can also get a pre built package from https://github.com/htm-community/htm.core/releases.  Download and expand the .zip for windows.  In the py folder will be the wheel file.
```
pip --user --force install  <wheel file name>
```

More instructions on how to install using pip are at https://packaging.python.org/tutorials/installing-packages/

**Comment by be4pro** [comment]
Thanks, @dkeeney. I'll update it once I found the solution.

**Comment by dkeeney** [comment]
@be4pro, sorry I did not see your post until just now...
The `python setup.py configure` will only do the configure step and build the dependencies but will not build the htm.core libraries or install them for use by python.

To do that we need to do `python setup.py install --user --force`  in order to get the rest of the build.
which is what was giving you the error...

I tried installing `Visual Studio Code` here on my machine.  (I needed to do that to update the README.md to include that IDE).  But that did not cause any problems with the python build.  So, I do not know what is different between our environments.

It is curious that you were able to get the `configure` to work.  That command needs the MSVC C++ compiler and the MSVC C compiler, and `setup.py` must have been able to find them.  So I suspect that the text of the error you are getting has nothing to do with the real error. But I do not know what that might be.

Another long shot, what do you get if you enter this command on a command prompt?
`C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -legacy -prerelease -format "json"`

**Comment by be4pro** [comment]
> The python setup.py configure will only do the configure step and build the dependencies but will not build the htm.core libraries or install them for use by python.

I copied the htm folder from Release/disr/ to Python's site-package, and it seems to work OK. Will that lead to some issues?

The output of `C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe -legacy -prerelease -format "json"` goes
>[
  {
    "instanceId": "f3be3794",
    "installDate": "2019-10-05T21:10:38Z",
    "installationName": "VisualStudio/16.3.5+29411.108",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\
\Community",
    "installationVersion": "16.3.29411.108",
    "productId": "Microsoft.VisualStudio.Product.Community",
    "productPath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Comm
unity\\Common7\\IDE\\devenv.exe",
    "state": 16600825988120575,
    "isComplete": true,
    "isLaunchable": true,
    "isPrerelease": false,
    "isRebootRequired": false,
    "displayName": "Visual Studio Community 2019",
    "description": "Powerful IDE、Free for students & personal usage",
    "channelId": "VisualStudio.16.Release",
    "channelUri": "https://aka.ms/vs/16/release/channel",
    "enginePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\
resources\\app\\ServiceHub\\Services\\Microsoft.VisualStudio.Setup.Service",
    "releaseNotes": "https://go.microsoft.com/fwlink/?LinkId=660893#16.3.5",
    "thirdPartyNotices": "https://go.microsoft.com/fwlink/?LinkId=660909",
    "updateDate": "2019-10-16T03:00:54.5476054Z",
    "catalog": {
      "buildBranch": "d16.3",
      "buildVersion": "16.3.29411.108",
      "id": "VisualStudio/16.3.5+29411.108",
      "localBuild": "build-lab",
      "manifestName": "VisualStudio",
      "manifestType": "installer",
      "productDisplayVersion": "16.3.5",
      "productLine": "Dev16",
      "productLineVersion": "2019",
      "productMilestone": "RTW",
      "productMilestoneIsPreRelease": "False",
      "productName": "Visual Studio",
      "productPatchVersion": "5",
      "productPreReleaseMilestoneSuffix": "1.0",
      "productSemanticVersion": "16.3.5+29411.108",
      "requiredEngineVersion": "2.3.2283.19382"
    },
    "properties": {
      "campaignId": "",
      "channelManifestId": "VisualStudio.16.Release/16.3.5+29411.108",
      "defaultProgram": "VisualStudio.f3be3794",
      "nickname": "",
      "setupEngineFilePath": "C:\\Program Files (x86)\\Microsoft Visual Studio\\
Installer\\vs_installershell.exe"
    }
  },
  {
    "instanceId": "VisualStudio.14.0",
    "installationPath": "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\
",
    "installationVersion": "14.0"
  }
]

**Comment by dkeeney** [comment]
Thank you for the output of vswhere.  It looks very much like the one I get from my system. The script is looking for "VisualStudio.16" when determining if Visual Studio 2019 is installed and it definitely should find it.  So unfortunately this gives us no clues.

I have to think about what else to try...

**Comment by be4pro** [comment]
Thank you for your help, @dkeeney. So I can run `configure` fine means setup.py did find MSVC C++ and C compiler on my computer. It's just something wrong while running setup(). Did I understand it correctly?

Also as mentioned, I copied the htm folder from Release/disr/build/ to Python's site-package, and it seems to work OK. Will this lead to some issues?

I want to build it instead of installing a pre-built wheel from PYPI(it works for me, btw) because I'd like to use the latest version.

**Comment by dkeeney** [comment]
> It's just something wrong while running setup(). Did I understand it correctly?

Yes, that is correct.  Inside setup.py it calls CMake to perform the configure, build, and install of the core library and then CMake will build the extension shared libraries from that.  It is the setup( ) function within setup.py that takes the extension libraries, and other things, and packages them into a .egg file that can be added to your site-package.  The building of the .egg with an extension requires a C program to which the libraries link to. That is the dummy.c that is giving you the problem.  The actual setup( ) function is part of the distutils package. It is not our code.

The only difference between the way that CMake is called in startupMSVC.bat and from setup.py is that the setup.py includes "-DBINDING_BUILD=Python3" as a runtime option telling CMake to also build the five extension libraries that are placed into `build\Release\distr\src\htm\bindings\*.pyd` ready for the setup( ) function.

So CMake is finding the compiler but the setup( ) function in distutils is not.

> I copied the htm folder from Release/disr/build/ to Python's site-package

Well, this is not the normal way to install a package. I am surprised that it worked at all.  If you run `pip list` does it show the package?

**Comment by dkeeney** [comment]
OH!!! That explains a lot.
Very good job 🥇 

So now, how do we fix this...
- We could tell new users to install Visual Studio 2017 in addition to 2019.
- We could tell them to add the patches to change the paths as you suggest.
- We could include some sort of code in setup.py that changes the paths... Then back it all out when distutils gets updated.

Let me do some research and see if this change is coming in the next release of Python.

**Comment by dkeeney** [comment]
Thanks to @be4pro who pointed me in the right direction.... I discovered that we should be using setuptools rather than distutils to do the installation and packaging.  I thought we WERE using setuptools but maybe I am not calling it correctly since he is getting that error in _msvccompiler.py which is part of distutils.  https://setuptools.readthedocs.io/en/latest/setuptools.html

I suspect that setuptools, being newer, will do a better job of finding Visual Studio 2019.  However, it could be that setuptools uses parts of distutils to package the extensions. That I need to find out.
So, let me play with that for a while and see if all we need is a change in some parameters.

**Comment by dkeeney** [comment]
@be4pro may I impose on you to try something for me...
Please edit setup.py, line 30 and change it from
```
from distutils.core import Extension
```

See # see https://stackoverflow.com/questions/44323474/distutils-core-vs-setuptools-with-c-extension

I don't see any indication in `C:\Program Files\Python37\Lib\site-packages\setuptools\msvc.py` that it supports anything newer that Visual Studio 2017 but it is worth a try to see if it can guess where 2019 is loacated.
to
```
from setuptools import Extension
```

**Comment by dkeeney** [comment]
Here MSVC 2019 is mentioned as working with setuptools:
https://wiki.python.org/moin/WindowsCompilers

setuptools package must be at least version 34.4.0
```
pip install --upgrade setuptools
```

**Comment by be4pro** [comment]
> Please edit setup.py, line 30 and change it from
> 
> ```
> from distutils.core import Extension
> ```
> 
> to
> 
> ```
> from setuptools import Extension
> ```

@dkeeney it worked perfectly well! So happy that you found out an elegant solution!

**Comment by dkeeney** [comment]
Ok, I will push this to the master.
Thanks for helping me find this.

**Comment by dkeeney** [comment]
@breznak I will be taking the weekend off.

**Comment by breznak** [comment]
@be4pro should be now fixed in master, could you please re-test?

**Comment by be4pro** [comment]
It works. :+1:

**Comment by breznak** [comment]
Thanks for both of you working hard on this! :+1: Closing as successfully resolved.
