### ISSUE TITLE
What should I do to get python build faster if I modify some cpp files?

### ISSUE THREAD

**Issue by be4pro** [htm-community/htm.core#744]
If I only modify a few lines in SpatialPooler.cpp, for example, do I have to build htm.core all over again running `python setup.py install`? It took quite some time. I guess there's an easier way to do it?

Sorry for this non-issue post, but I don't know how to ask in other forums. Thanks for your understanding.

**Comment by be4pro** [comment]
If I delete algorithms.xxxxxx.pyd from src/ and run `python setup.py install`, it will not only build a new one but also other pyd files.

**Comment by breznak** [comment]
> do I have to build htm.core all over again running python setup.py install? It took quite some time

First, you'd need to use `python setup.py install --force`

I don't think it rebuilds it ALL, only the needed/related parts (which is still quite a lot since SP is a core part). 
You might have a look at the "Developer build" in Readme, the one with `cmake , make -j8 etc` if that'd be faster. 

PS: ok to ask here.

**Comment by dkeeney** [comment]
There is a known problem with CMake in that if the sources for only one of the pyd files changes it still re-construct all pyd libraries.  There is something about the dependencies that is not quite right. I have looked for his bug several times without success.  Perhaps someone with a fresh eye will see something I have missed.

 Also, if you don't delete at least one of the pyd files it will not rebuild anything.  That is because there is a check in setup.py that if all pyd files exist it does not even call CMake. If that check was not there then it would take a long time re-building the libraries even if all you need to do is re-install the python modules.  I don't know if that check should be there or not.

But regardless, yes, it still takes a long time to rebuild the extension libraries if you change one .cpp file.

**Comment by be4pro** [comment]
Much appreciated for your help and time, @breznak and @dkeeney. I'll close this post and simply take the time to rebuild the libraries for now.
