### ISSUE TITLE
Typo in date encoder

### ISSUE THREAD

**Issue by be4pro** [htm-community/htm.core#762]
https://github.com/htm-community/htm.core/blob/abe0a39e62d3b3ba1b89b821bada619247063cc2/py/htm/encoders/date.py#L306
Should this line be `if diff.days == 1`?
or
<pre>
if diff.days == 0:
    val = 1
    break
elif diff.days == 1:
    val = 1.0 - (float(diff.seconds) / 86400)
</pre>

**Comment by dkeeney** [comment]
I think this is correct.
line 306 is in the logic  where the input time is before or equal to the beginning of the holiday.  So, if the diff.days == 0 it would mean the input time is exactly at midnight or less than a day BEFORE the holiday start time. 

 If it happens to be exactly on the holiday start (at midnight) then diff.days == 0 but 'val' ends up being 1.0 because diff.seconds would also be 0.  `val = 1.0 - (float(diff.seconds) / 86400)`. 

The value of 'val' would get less as the input time gets earlier further before the holiday start. At one day before it becomes 0.0, so there is a smooth ramp up starting at 0.0 at midnight the day before the holiday and reaching 1.0 at midnight at the beginning of the holiday.

The logic at line 300 makes a smooth ramp from 1.0 to 0.0 during the day after the holiday.

I am porting this to C++ and as a part of that effort I will make sure there are some tests to verify that this works.

**Comment by dkeeney** [comment]
I did find something that is not quite right in the date.py  DateEncoder.

In the DayOfWeek section (line 115 of date.py) 
```
      p.minimum  = 0
      p.maximum  = 7
      p.periodic = True
```
The minimum and maximum should be 'inclusive' per the parameter descriptions.  So, this implies that the program will allow  8 days in a week.  But if I change the maximum to 6 as it should be, the computed size of the output buffer only allows room for 6 sets of bits rather than 7.

So, this may mean that there is some sort of bug in the ScalarEncoder which is used by the dateEncoder to actually turn values into bits in a buffer. 

It is possible that this could be causing problems with other sections including the holiday encoding.  I will report here when I determine what the problem actually is.

**Comment by dkeeney** [comment]
After finishing my port of the DateEncoder to C++, what I found was that there is an error in the holiday encoding.  What the existing code was doing was encoding the smooth ramp up correctly but the smooth ramp down down was the same as the ramp up and it should be a wrap in the other direction:
```
    notholiday = [1,1,1,1,1,0,0,0,0,0]  # Not a holiday
    holiday1   = [0,0,0,1,1,1,1,1,0,0]  # day before holiday
    holiday    = [0,0,0,0,0,1,1,1,1,1]  # day of holiday
    holiday2   = [1,1,0,0,0,0,0,1,1,1]  # day after holiday; This was  [0,0,0,1,1,1,1,1,0,0]
```

It probably makes no difference in the semantics of the pattern but to me his makes more since.
To fix this it takes two things.
- on line 187 make it periodic so that it will do the wrap
```
      p.minimum    = 0
      p.maximum    = 2    <== changed this to a 2
      p.radius     = 1
      p.periodic   = True     <== Added this line
      p.activeBits = holiday
```
- on line 303, add rather than subtract the difference.
```
            # ramp smoothly from 1 -> 0 on the next day
            val = 1.0 + (float(diff.seconds) / 86400)  <== changed - to +
            break
```
Of course I also had to fix the unit tests.

This change will be in the PR that adds the C++ implemented DateEncoder.

**Comment by dkeeney** [comment]
Also note that what I thought was a bug in the ScalarEncoder was more of an error in documentation. The documentation states that the minimum and maximum configuration parameters are 'inclusive'. However, in periodic mode, the minimum is 'inclusive' but the maximum is 'exclusive'.  That is why it ranges from 0 to 7 in the DayOfWeek encoder and 0 to 2 in the Holiday Encoder.   So I added some comments to that effect in the ScalarEncoder.

**Comment by breznak** [comment]
..so, is this still an issue, or fixed in the PR above? (thx btw :) )

**Comment by dkeeney** [comment]
Welcome back @breznak 
No, this is working fine.  It just needed some clarification of what the end-points should be in that case.
