### ISSUE TITLE
HTM.core clone error. Setup.py cannot be installed and import.sdr is not working

### ISSUE THREAD

**Issue by kkaraoglan** [htm-community/htm.core#764]
I use pycharm.
I have both python 3.7.5 (x64 and x86) as interpreter on win10

I clone HTM.core files from the repository and loaded all the requirements. There is no error at this stage.

However, when I install with setup.py --user - force, I get an error and cannot proceed.

I use pycharm instead of Anaconda platform now .:slight_smile:
I have both python 3.7.5 (x64 and x86) as interpreter.

I clone HTM.core files from the repository and loaded all the requirements. There is no error at this stage.

**However, when I install with setup.py --user - force, I get an error and cannot proceed.**

And also still import.sdr is not working. Could you help me?

**Comment by dkeeney** [comment]
Thanks for adding this problem to the issues so we can track it.

I assume that by ` setup.py --user - force` you really mean ` python setup.py install --user --force`.   The --force is to force the install to replace whatever was there before from a previous load that might not have completed.  Alternatively you can use `pip uninstall  htm.core` to make sure nothing is already there.

I was setting up vertualenv for myself so I can switch between  the pythons.   I will continue to work on this.

**Comment by dkeeney** [comment]
So I have standard python3.7 and python3.8 running under virtualenv now.

Oh, by the way, we don't support 32bit python (x86), it only works with the 64bit python (x64).

The first thing I discovered is that when using virtualenv is that we don't need to use "--user --force" in our build command.  An you probably don't need to use it with pycharm either. 

Ok, now let me see if I can get Anacondra running under virtualenv.

**Comment by dkeeney** [comment]
This might be helpful in setting up multiple pythons:  https://www.freecodecamp.org/news/installing-multiple-python-versions-on-windows-using-virtualenv/

**Comment by dkeeney** [comment]
Ok, got it working with Anaconda python under Windows.  I think we were trying to make this more complicated than it should have been.  There is no need for virtualenv or pycharm since the `Anaconda Prompt` does the same thing for Anaconda python.

You will have to build from sources because the pre-built packages are for standard python3.7.  So you need to download the repository or clone it.

1) open the `Anaconda Prompt`, NOT the normal Command Prompt.  Look in your start menu under 'Anaconda3 (64bit)`.
2) cd to the htm.core repository that you downloaded or cloned.
3) run `python setup.py install`

That should run successfully.  You are ready to go.
To run the unit tests do the following:
```
  python setup.py test
```

**Comment by kkaraoglan** [comment]
Thank you so much. Problem is solved. I can code on both anaconda and pycharm.
