### ISSUE TITLE
unable to install htm.core from pip

### ISSUE THREAD

**Issue by ghantasalar** [htm-community/htm.core#829]
am using Python3 and tried to  installing htm.core ( v2.1.15 release).
As advised [here ](https://test.pypi.org/project/htm.core/) I tried the following command:

pip install -i https://test.pypi.org/simple/ htm.core

and ended up with the below error. Highly frustrating…please help.

RXG3200@C91194BB54C955 ~
$ pip install -i https://test.pypi.org/simple/ htm.core
Looking in indexes: https://test.pypi.org/simple/
ERROR: Could not find a version that satisfies the requirement htm.core (from versions: none)
ERROR: No matching distribution found for htm.core

RXG3200@C91194BB54C955 ~

**Comment by dkeeney** [comment]
@breznak are we still on the test PyPi?

**Comment by breznak** [comment]
@ghantasalar probably your system doesn't match the (limited) requirements for our pypi installs. 
What's your platform, bitness, python version, pip version...? 

You can try downloading the `.whl` from our Releases page (tab here) and install with pip from it. 

Currently, if you're on 64bit linux, python 3.7, x86 platform and any reasonably recent distro, you should be good to go. 

If not, try our source installs, the process is rather easy and it'll get you running anywhere. 

> are we still on the test PyPi? 

yes, until the process is finalized, I'm keeping it to test.pypi. 
Apropos, do we have the account to PYPI? or was it Matt's?

**Comment by ghantasalar** [comment]
Thanks for the responses.

@breznak  Unfortunately, I could not locate the .whl on the Releases (you did try to include the hyperlink but it is missing the underlying link).

As I am new to HTM, would like to focus my energy in learning about HTM rather then spending cycles for just installing the product...
As such, could you please include all steps for installing the htm.core including the hyper-links, if any. Greatly appreciate your time and help. 

My env, is : Python 3.8 on Linux 64bit.

**Comment by indy-3rdman** [comment]
@ghantasalar, another way to get you started might be this jupyter docker image, which I've just updated to include version 2.1.15 yesterday. It's available here: [https://hub.docker.com/r/3rdman/htm.core-jupyter](https://hub.docker.com/r/3rdman/htm.core-jupyter)

**Comment by breznak** [comment]
@indy-3rdman Indy, I like the idea with Jupyter notebook for 1st play-ground experience with HTM! :+1: (the Docker is nice too but since some past time I'm not too keen of fixed images - they keep getting out of sync). 
Anyway, the Jupyter notebook could work online (w/o any docker), since we're now on PyPI, right? Might be nice to add, would you like to make a PR? 

>  would like to focus my energy in learning about HTM rather then spending cycles for just installing the product...
As such, could you please include all steps for installing the htm.core including the hyper-links, if any.  

@ghantasalar I also rather spend my time on research... So which section of the Readme Installation process do you think needs improvement? Ideally suggest improvement in a PR. 

> My env, is : Python 3.8 on Linux 64bit. 

if you see again my answer above, you cannot install from PyPI because there we currently have only py3.7 whl binaries. So you have 2 choices, switch your env to py3.7 and install from pypi, or build from source on py3.8. 
Good point is that it'd be good to have binaries for py3.8, but there is a small issue blocking the automation yet #820

**Comment by indy-3rdman** [comment]
@breznak, is this what you have in mind?

[![Binder](https://mybinder.org/badge.svg)](https://mybinder.org/v2/gh/indy-3rdman/htm.core/master)

**Comment by breznak** [comment]
I'm closing the issue as Won'tfix since we provide PyPI wheels for py3.7 only, so far. Please comment,reopen if needed.
