### ISSUE TITLE
Value-class with getArray()?

### ISSUE THREAD

**Issue by Thanh-Binh** [htm-community/htm.core#839]
Hi all developer,
in the old version of htm.core, the class Value has a userful function getArray() that allows us to get an array from application into the regions like
```
myRegion(const ValueMap& params, Region *region) : RegionImpl(region)
{
....
Real32 *bufSC = (Real32 *)params.getArray("my_external_array")->getBuffer();
....
};
```
Unfortunatelly, I can not find it in the current version.
Do you have any function for doing this task?
Thanks

**Comment by dkeeney** [comment]
The ValueMap is the same as a Value object.
```
using ValueMap = Value;
```
It represents the parsed parameters.  Since the parameters are Yaml or JSON which has scalars, sequences and maps, this Value structure also could be a scalar (a  std::string), sequence (a std::vector) or a map (std::map).  The functions `isScalar( ), isSequence( ), and isMap( ) tell you the type of a Value object. Each node of a Value containing a sequence or a map is another Value object.  So any value that can be described with Yaml or JSON can be parsed into a tree of Value objects.  This could not be done with the old Value class.  All of the old capability still exists although it is a slightly different syntax.

For your example, use the following:
```
Real32 *bufSC = params.asVector<Real32>( ).data();
```
The data type conversion happens when you use the Value rather when it is parsed so there is much more control on the data types that you can get (it is not dependent on the spec any more).  At the top of htm/ntypes/Value.hpp source file there is documentation for all of the functions available on the Value object.

I considered the Value (and ValueMap) as internal objects and was not expecting to directly affect anyone.  If I broke your code I apologize.

**Comment by Thanh-Binh** [comment]
I found the solution like:
```
auto bufSC = params["my_external_array"].asVector<double>();
```

**Comment by Thanh-Binh** [comment]
Thanks David
