### ISSUE TITLE
How to save Predictor ?

### ISSUE THREAD

**Issue by vaibhavch** [htm-community/htm.core#876]
https://github.com/htm-community/htm.core/blob/master/bindings/py/cpp_src/bindings/algorithms/py_SDRClassifier.cpp

I see that Pickle support is not implemented yet. But is is necessary to persist trained classifier. is there any hack around to to save Predictor object somehow?

**Comment by breznak** [comment]
> I see that Pickle support is not implemented yet. But is is necessary to persist trained classifier. is there any hack around to to save Predictor object somehow? 

https://github.com/htm-community/htm.core/blob/master/src/htm/algorithms/SDRClassifier.hpp#L238 

Both support `Serializable`, so you can use the standard (cpp and exported to pybindings) way to serialize our objects. 
Pickle might not be implemented (PR welcome) but that's not the main method to serialize HTMcore from py. 

Please reopen if you think the issue is still valid.
