### ISSUE TITLE
Potential problem with the TM model

### ISSUE THREAD

**Issue by YounesBouhadjar** [htm-community/htm.core#935]
I'm facing the following problem with the TM model:

I trained the model using two simple sequences ``DABE`` and ``ABC``. 
During training, I expose the TM to the two sequences consecutively for a number of iterations and I reset the TM every time I  switch to the other sequence.

After sufficient training, when exposing the TM to the element `B` in the context of either sequence 1 or 2, the TM still predicts both `E` and `C`. Shouldn't the model predict only `E` when the `B` is presented within the context of the first sequence (``DABE``)? 
For the second sequence, I guess, this can be explained by the bursting of `A` which activates both `B1` and `B2` (`B1` and `B2` refer to the context of `B` in sequence 1 and 2 respectively).

You can find the script [here](https://github.com/YounesBouhadjar/htm.core/blob/master/py/htm/examples/tm/example_tm.py), to reproduce this behaviour. This script is a modified version of the `tm_high_order.py`.

**Comment by YounesBouhadjar** [comment]
Yes, I understand why you get predictions for both `C` and `E` in the context of the sequence `ABC`. But my question was more about when `B` is presented within the context of the sequence `DABE`, in this case, I also get predictions for both `C` and `E`.

**Comment by ctrl-z-9000-times** [comment]
After resetting the TM the next input will always burst, which activates every possible context for the input.
The reset function is like a wild card `.*` in a regular expression, matching every possible context.
Wildcards match anything / everything.
So the TM learns your sequences as:
`.*DABE`
`.*ABC`

Both sequences match the input `DAB`. `ABC` matches because the wildcard matches `D`.
In the TM, all learned sequences are assumed to start with such wildcards.

**Comment by ctrl-z-9000-times** [comment]
The problem is that `A1` is a subset of `A[burst]`.

---

Here is a demonstration:

```python
def showPredictions(sequence):
    ...
    print('num active cells', len(tm.getActiveCells().sparse)) # Append this line to showPredictions

sequences = [
  "DAB",
  "EAC",
  "FAD",
]
x, y = trainTM(sequences, iterations=200, noiseLevel=0.0)
print("show prediction sequence 1")
print("--------------------------")
showPredictions("A")
print("show prediction sequence 2")
print("--------------------------")
showPredictions("FA")
```

This should show that:
1. The pattern `A[burst]` contains 320 active cells, and predicts all three of the possible next letters.
2. The pattern `A in the context of F[burst]` contains 40 active cells, and predicts only `D`
3. The 40 cells from the `A in context of F[burst]` are a subset of the 320 cells from `A[burst]`, so `A[burst]` causes the TM think that it has just seen the context `F[burst]` even though it has not.

Now imagine giving the TM a new sequence to learn: `AX`.
The new sequence starts with `A` but really it starts with `A[burst]`, and that will make the TM think that the sequence actually starts with  `A in context of F[burst]` because that is a subset of `A[burst]`. And so the TM will learn this (wrong) context to think that the sequence is `FAX`. It will also learn the other variants: `DAX` and `EAX`.

**Comment by YounesBouhadjar** [comment]
right, I see. I thought as well along the same lines. I wonder though if such behaviour is biological? although this question is probably outside the context of this conversation, I can follow up on this on another occasion.

**Comment by ctrl-z-9000-times** [comment]
You're right, resetting the TM is not biologically plausible.
I think the only time that a real animal intentionally "resets" its brain is when they go to sleep & wake up.

But resetting the TM can be useful for running controlled experiments on the TM, and forcing it to learn specific things.

**Comment by YounesBouhadjar** [comment]
Something else, in case I add a noisy component between the two sequences like: `.DABE!ABC!DABE!ABC...`, (! denotes the noisy component),  what would be the prediction here when presenting `B` within the two different contexts? here I guess only `C` gets predicted when `B` is presented within the context of `DAB`, right? this is something I would like to test.
