### ISSUE TITLE
SDR's constructor does not support htm.bindings.engine_internal.Dimensions

### ISSUE THREAD

**Issue by HMaker** [htm-community/htm.core#941]
I tried to get output dimensions from a region to create a SDR
```python
from htm.bindings.sdr import SDR
from htm.bindings.engine_internal import Network

net = Network()
tm = net.addRegion('tm', 'TMRegion', str(dict(cellsPerColumn=16)))
# run network
active_cells = SDR(tm.getOutputDimensions('activeCells'))
active_cells.dense = tm.getOutputArray('activeCells'))
```
but `SDR()` is not compatible with `engine_internal.Dimensions`

**Comment by dkeeney** [comment]
The SDR( ) constructor is expecting a vector because this could be a multidimensional SDR.
Converting a Dimensions object to a vector requires the asVector( ) function. 
```
SDR(tm.getOutputDimensions('activeCells').asVector())
```

However, I don't think this is what you want.  To execute a Network, use the run( ) command.
```
net = Network( )
tm = net.addRegion('tm', 'TMRegion', "{cellsPerColumn=16}")
net.run(1)
active_cells = tm.getOutputData("activeCells")
```

But even this is not very useful because you have not given it any data.
Normally you would add an encoder region, then an SP region, and then a TM region and link the data flows together.
You can do that by calling the addRegion( ) for each region you want to add to the network, add link( ) calls to connect the data flows, and then call run(1 ).

Or you could configure the regions using the net.configure( ) function.  See py/tests/networkapi/sinewave_test.py

I hope that helps.

**Comment by dkeeney** [comment]
There is also a wiki that you might find useful:

   [NetworkAPI](https://github.com/htm-community/htm.core/blob/master/docs/NetworkAPI.md)

**Comment by HMaker** [comment]
> The SDR( ) constructor is expecting a vector because this could be a multidimensional SDR.
Converting a Dimensions object to a vector requires the asVector( ) function.
`SDR(tm.getOutputDimensions('activeCells').asVector())`

@dkeeney  I tried
```Python
from htm.bindings.engine_internal import Dimensions
Dimensions(1, 2).asVector()
```
and got `AttributeError: 'htm.bindings.engine_internal.Dimensions' object has no attribute 'asVector'`

**Comment by dkeeney** [comment]
@HMaker the asVector( ) function is now available in the master branch.  Please re-clone htm.core and build from sources.  Let us know if this satisfies your needs.

**Comment by HMaker** [comment]
Thanks for your work on this.
