### ISSUE TITLE
Understanding hotgym.py code parameters

### ISSUE THREAD

**Issue by suppathak** [htm-community/htm.core#964]
I am trying to apply [hotgym.py](https://github.com/htm-community/htm.core/blob/master/py/htm/examples/hotgym.py) code for detecting anomalies on my data. However, I am having some difficulty in understanding the parameter values as given in the code (attached screenshot)
![Screenshot from 2022-01-21 08-26-47](https://user-images.githubusercontent.com/30439457/150564070-3bbf0773-88fb-4e64-872c-6def18b913d1.png)
. 
I go hold of this [document](https://3rdman.de/2020/02/hierarchical-temporal-memory-part-1-getting-started/) which gives me some informations about parameters involved. 

I want to know if there is any document that would help me understand the anomaly code better so that I can play around with it. Please help me with some links.  

Thanks!

**Comment by dkeeney** [comment]
I suggest starting with HTM School; [https://numenta.com/htmschool/](https://numenta.com/htmschool/)
That does not talk about the parameters directly but give you an understanding of the theory so that you can better choose parameter values.  Many of the default parameters are 'OK' for the hotgym example but could use some optimizing.

Keep in mind that the predictor is not using HTM technology. It uses classical NN and therefore it requires a LOT more training that the other HTM algorithms.  So if you are relying on the predictor (or the underlining Classifier object) then use lots of training before considering its results.

**Comment by suppathak** [comment]
Thank you @dkeeney . I have gone through the link you have shared. It gave be a good understanding of how HTM works. I would say, It gave me a good intution behind the theory.

The problem that I am facing presently is I am not able to find any good reference for using anomaly detection code. The only practical reference I have is hotgym.py code. I would really appreciate if anybody can share some more reference examples where people have applied this anomaly detection code.
